### ISSUE TITLE
jvb not working in containers with same usual setting

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-ofmeet-plugin#112]
I did the following

Upgrade existing OF database or restart with a fresh DB but same result. P2p connections are fine but not JVB. It is green in ofmeet and nothing show up in logs.
The only errors i trapped are via the console when 3rd user join the call.

Unsure if i miss something but this works with padé plugin with exactly same settings.

Any clue ? 

BTW firefox is working

@dele, i can provide you access if needed to have a look

![screenshot11](https://github.com/user-attachments/assets/0a2ae5bc-1249-4a0f-ab4a-735895d750f1)
![screenshot10](https://github.com/user-attachments/assets/ce18abcb-3437-42c0-bc99-ef5ef8bca902)

**Comment by deleolajide** [comment]
> this works with padé plugin with exactly same settings.

The latest Jitsi code does not work any more with Pade. This may require re-configuration of some ports in your container to make the websocket proxy to work. I suggest you enable trace looging in Openfire to see all Jitsi log messages and enable you debug the issue.

**Comment by gjaekel** [comment]
Apart from this I want to remember that the websocket proxy implementation inside Pàde is still broken. It may be used for first tests, but it will mangle connections under real load.

**Comment by ClaudeStabile** [comment]
I have restarted openfire with traces and clean logs just before testing with a vidconf named testclaude and add 3 participants.
I did not found yet the root cause for the bridge websockets connection failure.

Of course we may need to change the docker container port opening that is probably the reason it works on your local machine and not through the container as padé.

I will check, if you find something relevant, let me know and we test that

++

[openfire-debug.log](https://github.com/user-attachments/files/17326510/openfire-debug.log)

**Comment by ClaudeStabile** [comment]
Dele,

issue i have looks similar to this thread at jitsi : https://github.com/jitsi/docker-jitsi-meet/issues/1531 unsure if we need to set JVB_ADVERTISE_IPS or ?

hope it helps a bit

Thanks

**Comment by ClaudeStabile** [comment]
I have notice that now Jitsi is managing these connections via reverse proxy. This is probably the root cause for that prob. I will have a look at that. Usually i use haproxy to do the dispatch job with containers. Unsure if i can adapt it but that's clearly the problem. I also use nginx for mastodon instances i may have to do someting similar.
The ofmeet code is not concerned as it is working. Same kind of isssue will probably occur with public cloud install as reverse proxy needs to be specially set for that.
see this :
https://www.claudiokuenzler.com/blog/1405/how-to-run-jitsi-video-conference-server-behind-nat-reverse-proxy

Investigating this.... I hope i can get it fixed adn working. 

++

**Comment by ClaudeStabile** [comment]
I am searching to make ofmeet work behind reverse proxies...

Something else i notice there are still reference to Padé in config.js at least :

![screenshot13](https://github.com/user-attachments/assets/522a39c3-f41e-4b58-81d6-578768e43138)

**Comment by deleolajide** [comment]
![image](https://github.com/user-attachments/assets/3b82293b-7cab-4685-806e-6404a1be9b45)

I have enabled SCTP (webrtc data channel)  as an alternative to colibr-websockets using as communication between JVBs. I tested on my WSL (Ubuntu) and it is working. make sure it is enabled in ofmeet. 

By default, it is enabled for Linux and diasbled for Windows. It should fix the errors shown in the screenshot. If it it is still not working, open a new issue with the new log file error.

![image](https://github.com/user-attachments/assets/6640c1df-d7d4-4404-a1aa-b1a5c33a91dc)

**Comment by ClaudeStabile** [comment]
Dele,

I cannot enable that with alpine containers, it does not work. I need to try out with ubuntu based containers or understand why alpine sontainers does not support webrtc channels possibly simply a package missing.
If you know what ubuntu package is used for webrtc channels it could help my understanding

Thanks for input, i need data channels to do same as you did.

Additionnal question : any chance to have websocket connectivity supported or is it a problem ?



++

**Comment by ClaudeStabile** [comment]
@deleolajide 
Good point with data channels it works !

I manage to make the bridge work 3+ participants with chrome it works now
I have to rebuild an openfire container based on ubuntu and not alpine. I try to add what is missing to alpine but no sucess for now. I rebuild an ubuntu container, this works.

What i have found also : 

With firefox or android mobile same behavior camera is grey and searching, it does not work

Feel free to try out or have a look with https://meet.free-solutions.ch  console is 9291

With firefox or android i have black screen and cam+mic keep searching like this : 
![screenshot4](https://github.com/user-attachments/assets/6b2dfb02-d7a9-43d4-a555-036433eeae80)

On android :

![ofmeet1](https://github.com/user-attachments/assets/56045659-2129-4075-8e76-40d92f5703c2)
Is there any chance we can bypass the app choice screen ? Would be nice to go direct via web as with Padé.
Stack trace on android, still referring to /pade why ?
![ofmeet2](https://github.com/user-attachments/assets/b1a3b8c8-fcef-4be2-85da-56f44f9204dc)

Thanks in advance for hints and clues, it helps... datachannel mandatory was the one for jvb to work.

++
