### ISSUE TITLE
How to fix the vedio permission for ofmeet on iframe

### ISSUE THREAD

**Issue by zengxianduan** [igniterealtime/openfire-ofmeet-plugin#93]
hi,i'm testing the ofmeet on my project.
i have trouble when i integrate the url https://my-server.7443/ofmeet/xxx 
to layUI.
it seems it's a frame,so it can't get the video and microphone permissions.
could you give me a tip to solve the problem?
this is my usage.
layer.open({
			type: 2,
			title: 'openfire meeting',
			shade: false,
			maxmin: true,
			area: ['90%', '90%'],
			content: 'https://my-server:7443/ofmeet/test'
		});

**Comment by GregDThomas** [comment]
I don't know, but it's certainly worth setting the Openfire system property 

`adminConsole.frame-options` to 
`allow-from https://example.com/`

where https://example.com/ is the base URI of the server hosting the frame - note that there no path details, just protocol, host and port (if not the default). More details on what this option does are at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by deleolajide** [comment]
Read this https://wisej.com/support/question/support-allow-camera-and-microphone-in-iframe

**Comment by zengxianduan** [comment]
yes，i'm trying to fix it.it seems that i need to add property on iframe
