### ISSUE TITLE
Multiplayer video doesn't work?

### ISSUE THREAD

**Issue by zengxianduan** [igniterealtime/openfire-ofmeet-plugin#95]
it doesn't work when three or more people join in the same room.
The last one can share video herself.
But,the other's video will miss.
it seem that the ofmeet only support p2p?

**Comment by zengxianduan** [comment]
it'work when i set system params just like
![image](https://user-images.githubusercontent.com/35206762/56182145-58c6a700-6043-11e9-90a2-0c6fcf149e28.png)

**Comment by wrooot** [comment]
Please, use forums for support requests. GitHub issues should only be used to report actual bugs and feature requests. https://discourse.igniterealtime.org/c/openfire-plugins/openfire-meetings
