### ISSUE TITLE
Openfire-service.exe blocks https port 443 on Windows even if ofmeet is set to use only port 7443

### ISSUE THREAD

**Issue by bahanya** [igniterealtime/openfire-ofmeet-plugin#96]
It seems so if Openfire is installed on Windows and services inside OF using port 7443 are enabled and used, than the port 443 will be used along with port 7443, doesn’t matter if 443 is not set anywhere. With setting up a meeting e.g. using ofmeet the issue can be reproduced. The Web Application Server (Apache installed on the same machine in my case) won’t be able to manage (listen on) the standard https port anymore because OF will be hijacking the port 443 after the first call of such services of OF. It means openfire-service.exe will be allocating port 443, too. This is visible in Resource Monitor under tab Network. Please help to fix this issue, seems to be a hardcode somewhere in the code. I’m using OF version 4.3.2. Thanks!

**Comment by guusdk** [comment]
The behavior is slightly different from what you're describing, but I can see how it can be a nuisance. You will be able to reconfigure Openfire (Openfire Meetings, specifically), to change the behavior.

Openfire Meetings will attempt to exchange media data (audio/video) over TCP 443, but will fall back to 4443 if 443 is unavailable. This default behavior can be changed in the admin console. 

![image](https://user-images.githubusercontent.com/4253898/57211463-a39f6300-6fe0-11e9-877c-4339050a63b8.png)
Navigate to Meetings > Meetings  > Networking and scroll all the way down.

![image](https://user-images.githubusercontent.com/4253898/57211511-d0ec1100-6fe0-11e9-8fc5-bcfc5c66e2d5.png)
In the "Media traffic over TCP" box, provide a value for "Port number"

The description of that option describes how the setting is applied.

A side note: It's of importance to realize that depending on network conditions, different mechanisms / ports can be used to establish audio/video sessions. The setting that you're changing here might not be how data actually is exchanged between users of your network.
